name: am_start_to_intent_converter
description: "The am_start_to_intent_converter package is a Flutter library that simplifies the conversion and execution of Android am start commands as Flutter Intent objects."
version: 0.0.1
homepage: https://www.gihub.com/YatoNorai/AmStartToIntentConverter

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: am.start.to.intent.converter.am_start_to_intent_converter
        pluginClass: AmStartToIntentConverterPlugin
